### ISSUE TITLE
car number is not printing

### ISSUE THREAD

**Issue by ponnekantisvkrishna** [anuj-badhwar/Indian-Number-Plate-Recognition-System#1]
Hi
I am working on your code to print car number using.
I am working python 3.6 
I ran all steps and getting input image, morphed image, and number is not printing on morphed image like which you put in snapshot. 
I give print but number is not printing.
while executing contours= extract_contours(threshold_img) it go to infinite loop
can you please give suggestions on that.

**Comment by onuzbee** [comment]
`cv2.waitKey(0)` is being used in the `extract_contours()` method. It waits until a key is pressed on the keyboard and then returns the contours. Are you sure you are pressing a key? You should remove it to avoid pressing a key every time it is executed.

**Comment by iomutans** [comment]
Hi ,
    I am getting below error 

contours= extract_contours(threshold_img)
  File "main.py", line 56, in extract_contours
    im2,contours, hierarchy= cv2.findContours(morph_img_threshold,mode=cv2.RETR_EXTERNAL,method=cv2.CHAIN_APPROX_NONE)
ValueError: need more than 2 values to unpack

**Comment by Bilalsaghir** [comment]
I am getting the same error.


++++++++++++++++++++++++++
C:\Python27\python.exe C:/Users/Entrepreneur/Desktop/PI/Indian-Number-Plate-Recognition-System-master/main.py
DETECTING PLATE . . .
Traceback (most recent call last):
  File "C:/Users/Entrepreneur/Desktop/PI/Indian-Number-Plate-Recognition-System-master/main.py", line 143, in <module>
    contours= extract_contours(threshold_img)
  File "C:/Users/Entrepreneur/Desktop/PI/Indian-Number-Plate-Recognition-System-master/main.py", line 56, in extract_contours
    im2,contours, hierarchy= cv2.findContours(morph_img_threshold,mode=cv2.RETR_EXTERNAL,method=cv2.CHAIN_APPROX_NONE)
ValueError: need more than 2 values to unpack

Process finished with exit code 1
+++++++++++++++++++++++++++

**Comment by Bilalsaghir** [comment]
@iomutans and @anuj-badhwar can you please help to solve this out ???

**Comment by karthick-codehub** [comment]
`im2,contours, hierarchy= cv2.findContours(morph_img_threshold,mode=cv2.RETR_EXTERNAL,method=cv2.CHAIN_APPROX_NONE)`  


REPLACE TO 


`contours, hierarchy= cv2.findContours(morph_img_threshold,mode=cv2.RETR_EXTERNAL,method=cv2.CHAIN_APPROX_NONE)`
