### ISSUE TITLE
error while execution

### ISSUE THREAD

**Issue by KNITPhoenix** [anuj-badhwar/Indian-Number-Plate-Recognition-System#2]
![Screenshot from 2019-04-13 04-14-42](https://user-images.githubusercontent.com/33430392/56069930-e3d54200-5da2-11e9-8790-26a3fe3e52b4.png)

**Comment by harshil-darji** [comment]
In line number 55, remove im2 variable as it is useless.

**Comment by karthick-codehub** [comment]
`im2,contours, hierarchy= cv2.findContours(morph_img_threshold,mode=cv2.RETR_EXTERNAL,method=cv2.CHAIN_APPROX_NONE)`

REPLACE TO

`contours, hierarchy= cv2.findContours(morph_img_threshold,mode=cv2.RETR_EXTERNAL,method=cv2.CHAIN_APPROX_NONE)`
